# Generated by Django 6.0.5 on 2026-05-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_booking_quantity_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=64, unique=True)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('is_used', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_access', to='booking.booking')),
            ],
        ),
    ]
