# Generated by Django 6.0.5 on 2026-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_ownerprofile_company_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=12, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=12, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
