# Generated by Django 6.0.5 on 2026-05-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_quantity_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
